edition = "2021"
tab_spaces = 2
max_width = 70
array_width = 50
chain_width = 50
comment_width = 65
wrap_comments = true
fn_call_width = 50
fn_params_layout = "Vertical"
indent_style = "Visual"
brace_style = "AlwaysNextLine"
format_strings = true
enum_discrim_align_threshold = 30
reorder_imports = true
